domain_keywords:
  - reinforced concrete corrosion experiment
  - long term durability concrete
  - concrete chloride diffusion test
  - reinforcement corrosion long duration exposure
  - reinforced concrete half-cell potential experiment
  - accelerated corrosion test concrete
  - freeze-thaw concrete long term test
  - wet-dry cyclic exposure concrete experiment
  - reinforced concrete crack width over time
  - reinforced concrete mass loss rebar corrosion
domain_sources:
  - https://api.openalex.org
  - https://www.crossref.org
  - https://arxiv.org
  - https://scholar.google.com
  - https://ascelibrary.org
  - https://www.concrete.org
  - https://www.fhwa.dot.gov
  - https://data.gov
max_depth: 2
file_types: [pdf, html, docx, txt, csv]
year_filter: 1995
rate_limits:
  requests_per_minute: 30
  per_domain: 10
contact_email: your_email@example.com
contact_email: duydeptrai1611@gmail.com
