name: CI

on:
  pull_request:
    branches: [ main-next ]
  push:
    branches: [ feat/** ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint import
        run: |
          python -c "import yaml, requests, bs4, sqlalchemy, pydantic, feedparser, scrapy"
      - name: CLI help
        run: |
          python -m src.uwss.cli --help
      - name: Build parser smoke
        run: |
          python - <<'PY'
import sys
from src.uwss.cli import build_parser
p = build_parser()
assert p is not None
print('parser-ok')
PY

